### PR TITLE
added magnitude and alert facets for event data types

### PR DESCRIPTION
**Pull request by marjo-luc**

### CODE REVIEW

**Review by DustinKLo — APPROVED** [review]
~LGTM~ ~👍~

**Review by DustinKLo — CHANGES_REQUESTED** [review]
@marjo-luc wait you forgot a comma here
https://github.com/hysds/tosca/pull/27/files#diff-5391199b4fd734673aad2dd7dcd096590a994d0ae9123f6b629ac00114754486R308

**Review by marjo-luc — COMMENTED** [review]
Yikes! Thank you!

**Review by DustinKLo — APPROVED** [review]
@marjo-luc  perfect 👍 
you can squash and merge

**Pull request merged**
